name: built_value_basic_basic_tutorial
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Benjamin Lee <bnllee@ucdavis.edu>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  built_value: ^7.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  built_value_generator: ^7.0.0
  build_runner: ^1.7.0
  built_collection: ^4.3.0
